name: Run mlp test on requested platforms

on:
    workflow_call:
        inputs:
            conda_env:
                required: true
                type: string
                description: Name of conda env
            compiler:
                required: true
                type: string
                description: Type of JIT to use
            device:
                required: true
                type: string
                description: Type of engine to use
        secrets:
            DB_URL:
                required: true

jobs:
    mlp_test:
        runs-on:
            - self-hosted
            - glados
        strategy:
            matrix:
                bname:
                    - size2
                    - size3
                    - size4
                    - size5
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/initial_setup
              with:
                  conda_env: ${{ inputs.conda_env }}
                  compiler: ${{ inputs.compiler }}

            - name: Run MLP test on specific compiler
              shell: bash -el {0}
              run: |
                  benchmark-run \
                    --host spr \
                    --benchmark mlp \
                    -p "name='${{ matrix.bname }}'" \
                    --backend_desc "${{ matrix.bname }}" \
                    --compiler "${{ inputs.compiler }}" \
                    --device ${{ inputs.device }} \
                    -v --url ${{ secrets.DB_URL }}
